Adding reports and updating several Test

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -1,53 +1,103 @@
 name: Cypress Tests
 
 on:
+
   push:
     branches: [ main ]
+
   pull_request:
     branches: [ main ]
+
 jobs:
+
   cypress-run:
+
     runs-on: ubuntu-latest
 
+    strategy:
+
+      fail-fast: false
+
+      matrix:
+        browser: [chrome, firefox]
+
     steps:
+
       - name: Checkout repo
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Setup Node
         uses: actions/setup-node@v4
+
         with:
           node-version: 20
+          cache: 'npm'
 
       - name: Install dependencies
         run: npm install
 
-              
-      - name: debug env
-        run: |
-          echo "BASE_URL: $BASE_URL"
-          echo "API_URL: $API_URL"
-          echo "USER: $USER"
-          echo "PASSWORD: $PASSWORD"
-        env:
-          BASE_URL: ${{ secrets.BASE_URL }}
-          API_URL: ${{ secrets.API_URL }}
-          USER: ${{ secrets.USER }}
-          PASSWORD: ${{ secrets.PASSWORD }}    
-
       - name: Validate secrets
+
         run: |
-          if [ -z "$USER" ]; then echo "USER is empty"; exit 1; fi
-          if [ -z "$PASSWORD" ]; then echo "PASSWORD is empty"; exit 1; fi
-          if [ -z "$API_URL" ]; then echo "API_URL is empty"; exit 1; fi
+
+          if [ -z "$USER" ]; then
+            echo "USER secret is missing"
+            exit 1
+          fi
+
+          if [ -z "$PASSWORD" ]; then
+            echo "PASSWORD secret is missing"
+            exit 1
+          fi
+
+          if [ -z "$BASE_URL" ]; then
+            echo "BASE_URL secret is missing"
+            exit 1
+          fi
+
         env:
-          API_URL: ${{ secrets.API_URL }}
+          BASE_URL: ${{ secrets.BASE_URL }}
           USER: ${{ secrets.USER }}
           PASSWORD: ${{ secrets.PASSWORD }}
 
-      - name: Run Cypress tests
-        run: npx cypress run
+      - name: Run Cypress Tests
+
+        run: |
+          npx cypress run \
+          --browser ${{ matrix.browser }}
+
         env:
           BASE_URL: ${{ secrets.BASE_URL }}
           API_URL: ${{ secrets.API_URL }}
           USER: ${{ secrets.USER }}
           PASSWORD: ${{ secrets.PASSWORD }}
+
+      - name: Upload Mochawesome Report
+
+        uses: actions/upload-artifact@v4
+
+        if: always()
+
+        with:
+          name: mochawesome-report-${{ matrix.browser }}
+          path: cypress/reports
+
+      - name: Upload Screenshots
+
+        uses: actions/upload-artifact@v4
+
+        if: failure()
+
+        with:
+          name: screenshots-${{ matrix.browser }}
+          path: cypress/screenshots
+
+      - name: Upload Videos
+
+        uses: actions/upload-artifact@v4
+
+        if: always()
+
+        with:
+          name: videos-${{ matrix.browser }}
+          path: cypress/videos
